# Generated by Django 4.0.6 on 2022-08-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='vendor_req_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='vendor_store',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
